version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - HOST=0.0.0.0
      - PORT=8080
    depends_on:
      - db
    networks:
      - investutil-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-investutil}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - investutil-network

volumes:
  postgres_data:

networks:
  investutil-network:
    driver: bridge 